### ISSUE TITLE
Output file size in human readable format

### ISSUE THREAD

**Issue by kugelvlitz** [FarisHijazi/rarbgcli#1]
Current file size is only represented in bits which can be non intuitive to determine equivalent in kB/MB/GB. Expected format would be something similar to running ```df -h```

**Comment by FarisHijazi** [comment]
sounds like a good idea, would you be interested in making those changes? I'll be happy to accept them.

I'll keep the issue open, I might add this later

**Comment by kugelvlitz** [comment]
Awesome! I just installed from the latest commit and looks good. Wish I had taken some time to add it, but just never got to it 🙃 . Thanks for the awesome work on this project!
