### ISSUE TITLE
Searches for tvshows with dots in the name return strange results. Example S.W.A.T.

### ISSUE THREAD

**Issue by chew1309** [FarisHijazi/rarbgcli#2]
Searches for tvshows with dots in the name return strange results. Seems to be interpreting the dot as a wild card.

I tried ..

rarbg "S.W.A.T.2017.s06e04.1080p" -c tvshows -l 5 -r seeders --descending -m -nc > tmp.out

and

rarbgcli "S\.W\.A\.T.2017.s06e04.1080p" -c tvshows -l 5 -r seeders --descending -m -nc > tmp.out

and a bunch of different variations in between and it just comes back with a bunch of different tvshows ...

Other TV shows work fine.

cat tmp.out
magnet:?xt=urn:btih:60858e9777cb335a748a9e7ddbe7df20841afa3e&dn=The.Good.Doctor.S06E04.1080p.WEB.h264-GOSSIP%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2980&tr=udp%3A%2F%2F9.rarbg.to%3A2800&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12740&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13710
magnet:?xt=urn:btih:69b223b39acd4cbf080f5e87cedcd2031f859454&dn=S.W.A.T.2017.S06E04.1080p.WEB.H264-GLHF%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2740&tr=udp%3A%2F%2F9.rarbg.to%3A2900&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12800&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13740
magnet:?xt=urn:btih:069024369208b3c7973810e3e94d84e835d4d758&dn=Young.Sheldon.S06E04.1080p.WEB.H264-GLHF%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2800&tr=udp%3A%2F%2F9.rarbg.to%3A2970&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14720&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13780
magnet:?xt=urn:btih:1a354b5a5eb63abb7349e8915f4625889d7668bc&dn=SEAL.Team.S06E04.1080p.WEB.H264-GLHF%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2990&tr=udp%3A%2F%2F9.rarbg.to%3A2980&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13720&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15730
magnet:?xt=urn:btih:9fda05240a93ebdf69e2db827b6cfaf84eb0d38d&dn=The.Good.Doctor.S06E04.Shrapnel.1080p.AMZN.WEBRip.DDP5.1.x264-NTb%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2880&tr=udp%3A%2F%2F9.rarbg.to%3A2740&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14800&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15750

**Comment by FarisHijazi** [comment]
`-r seeders` seems to be the issue, it doesn't matter if the name has "." in it or not, it just seems to not match as strongly

this is the behavior of the website itself, not my script.
You can verify this by actually going to the website and pasting the exact search term and all the parameters and you'll see that you get the same result
