### ISSUE TITLE
Torrent files and magnets from other pages indicate different ones

### ISSUE THREAD

**Issue by pepitto89** [FarisHijazi/rarbgcli#3]
First of all thank you very much for this wonderful tool

Currently it seems that if you go from the CLI to a next page the torrent and the magnet do not match with the selected one, even if it is parsed.

`rarbgcli "marvel" --category movies -nc`

If we go to page 2 and select Aloha.2015.1080p.BluRay.H264.AAC-RARBG

`[
    {
        "title": "Aloha.2015.1080p.BluRay.H264.AAC-RARBG",
        "torrent": "https://rarbgunblocked.org/download.php?id=vo38etg&f=Marvel%20One-Shot%20-%20Agent%20Carter%202013%201080p%20Blu-ray%20Remux%20AVC%20DTS-HD%20MA%207.1%20-%20KRaLiMaRKo-%5Brarbg.to%5D.torrent&tpageurl=/torrent/vo38etg",
        "href": "https://rarbgunblocked.org/torrent/e78kyla",
        "date": 1525905367.0,
        "category": "movies",
        "size": 2029999999,
        "seeders": 1,
        "leechers": 2,
        "uploader": "Scene",
        "magnet": "magnet:?xt=urn:btih:d59d34638f5628dae5faa8ffa76d3e5fc576e612&dn=Marvel%20One-Shot%20-%20Agent%20Carter%202013%201080p%20Blu-ray%20Remux%20AVC%20DTS-HD%20MA%207.1%20-%20KRaLiMaRKo&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710"
    }
]`

Is it possible that they have changed the structure of the web?

**Comment by FarisHijazi** [comment]
Interesting, I didn't notice this, I'll get on it in a few hours
Thanks for specifying it, i can test this way
